apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-DM-Auth-Service
  annotations:
    github.com/project-slug: codeiain/openai-DM-AuthService
spec:
  type: openapi
  lifecycle: unknown
  owner: staff
  system: openai-DM
  definition:
    $text: /swagger.json
  providesApis: 
    - openai-DM-Auth-Service
  
