---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: openai-dm
  # annotations:
  #   backstage.io/techdocs-ref: dir:.
  #   github.com/project-slug: codeiain/openai-DM-character-service
spec:
  owner: me
---
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openai-dm-auth-server
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-AuthService
spec:
  type: service
  lifecycle: unknown
  owner: me
  system: openai-dm
  dependsOn:
    - resource:couchbase
    - resource:prometheus
  providesApis:
    - openai-dm-auth-api
---
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-dm-auth-api
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: codeiain/openai-DM-AuthService
spec:
  type: openapi
  lifecycle: unknown
  owner: me
  system: openai-dm
  definition:
    $text: /swagger.json

  
