apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-DM-AuthService
  annotations:
    github.com/project-slug: codeiain/openai-DM-AuthService
spec:
  type: service
  lifecycle: production
  owner: openai
  system: OpenAI-DM
  providesApis:
    - auth-service
