apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-DM-AuthService
  annotations:
    github.com/project-slug: codeiain/openai-DM-AuthService
spec:
  type: openapi
  lifecycle: unknown
  owner: staff
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
